# Neue Konzepte: Machine Learning
# Grundlagen


Bitte lesen Sie die folgenden Anweisungen sorgfältig durch und führen Sie die Befehle aus, um sicherzustellen, dass Ihre Einrichtung ordnungsgemäß funktioniert.

Wenn alles funktioniert, können Sie gerne ein wenig mit diesem Jupyter-Notebook experimentieren, um sich mit Jupyter vertraut zu machen und zu lernen, wie man damit arbeitet. Wir werden Jupyter-Notebooks während der gesamten Vorlesung verwenden.

## Ziele dieses Abschnitts
- Sicherstellen, dass Ihre Umgebung ordnungsgemäß funktioniert.
- Einen ersten Einblick in unsere Toolbox für dieses Modul gewinnen.
- In der Lage sein, Code in Jupyter zu schreiben und auszuführen.

## 1. Erste Schritte mit Jupyter

Jupyter ist das Werkzeug unserer Wahl für die Interaktion mit dem Python-Interpreter.

Mit Jupyter können Sie Python-Code in einer interaktiven Umgebung direkt in Ihrem Browser schreiben und ausführen. Mit Jupyter können Sie Abbildungen anzeigen, Ergebnisse mithilfe von Markdown-Funktionen dokumentieren und Ihre Ergebnisse beispielsweise im HTML-Format exportieren.

Jupyter-Notebooks bestehen aus „Zellen“, die kleine Text- oder Codeabschnitte enthalten (wie diese hier). Es gibt zwei Haupttypen von Zellen:
- **Markdown-Zellen** zur Dokumentation mit Markdown
- **Code-Zellen** für Python-Code

Eine neue Zelle ist immer eine Code-Zelle. Wechseln Sie den Typ, nachdem Sie Ihren Text in Markdown geschrieben haben, indem Sie zuerst `esc` und dann `m` drücken ODER indem Sie das Dropdown-Menü in der Menüleiste oben verwenden.

Zellen können durch Doppelklicken ODER durch Drücken von `Enter` bearbeitet werden.

Zellen werden immer durch Drücken von `Strg` + `Enter` (ausführen und Cursor nicht verschieben) oder durch `Umschalt` + `Enter` (ausführen und Cursor zur nächsten Zelle verschieben) ausgeführt. Sie können auch die interaktiven Werkzeuge oben im Jupyter-Notebook verwenden.

**Achtung**: Die Ausführungsreihenfolge in Jupyter ist wichtig! Wenn Sie frühere Zellen erneut ausführen, nachdem spätere Zellen Variablen geändert haben, können sich die Ergebnisse ändern!

Auf der linken Seite einer Zelle sehen Sie einen grauen Indikator, der Ihnen die Reihenfolge der letzten Ausführung anzeigt.

Wenn Sie „seltsame“ Effekte beobachten, versuchen Sie, das gesamte Notebook erneut auszuführen (`Ausführen -> Alle Zellen ausführen`)!

### &#x270d; Übung
Erstellen Sie eine neue Zelle unterhalb dieser und oberhalb der Linie.

Geben Sie eine einfache Berechnung ein, z. B.: 1 + 2 und führe sie aus.

Erstellen Sie anschließend eine weitere neue Zelle und stellen Sie sie auf Markdown um. Wir machen weiter, sobald dies bei allen funktioniert.

In [1]:
1+2

3

test markdown

---


## 2. Erste Schritte in Python
Die folgende Anweisung ist ein sehr einfaches Beispiel. Führen Sie sie erneut durch Drücken von `Umschalt` + `Eingabetaste` aus. Dabei wird lediglich die angegebene Zeichenkette ausgegeben. Sie können die Zeichenkette in der nächsten Zelle gerne ändern und den Befehl erneut ausführen.

In [2]:
print('Hello Word')

Hello Word


Das folgende Beispiel ist ein weiteres sehr einfaches Beispiel. Hier weisen wir zwei Variablen Werte zu, addieren diese und geben das Ergebnis aus. Hinweis: In Jupyter Notebook benötigen Sie den Befehl `print` nicht, um Ergebnisse auszugeben. Wenn ein Befehl ein Ergebnis zurückgibt, wird dieses automatisch ausgegeben!

In [3]:
a = 3
b = 4
a + b

7

Wenn Sie selbst Code schreiben oder mit diesem Notebook experimentieren, werden Sie wahrscheinlich auf Fehler stoßen. Python erklärt Ihnen in der Regel sehr klar, was in Ihrem Code schiefgelaufen ist. Dies wird durch den folgenden Befehl veranschaulicht:

In [5]:
a=1
c=2
a + c

3

Wie Sie sehen, geben die ersten Zeilen der Fehlermeldung einen Hinweis darauf, wo der Fehler aufgetreten ist. Die letzte Zeile beschreibt, warum er aufgetreten ist.

Versuchen Sie, diese Fehlermeldungen zu lesen! Oft führen sie Sie schnell zur Lösung, die Sie benötigen, um Ihren Code zu korrigieren.

---
### &#x270d; Übung
Korrigieren Sie die obige Anweisung so, dass sie ausgeführt werden kann!

---

## Importieren unseres Tool-Sets
Python verfolgt einen „Batteries included“-Ansatz – die Entwickler von Python möchten Ihnen alles zur Verfügung stellen, was Sie brauchen, damit Sie schnell produktiv arbeiten können! Um die Leistungsfähigkeit von Python voll auszuschöpfen, können wir Bibliotheken (z. B. „tools“) importieren, die alle möglichen Funktionen bereitstellen!

Im Laufe des Kurses werden wir mehrere Bibliotheken verwenden, die die Datenanalyse und -visualisierung, sowie die Implementierung von Algorithmen unterstützen. Überprüfen Sie, ob diese korrekt installiert sind, indem Sie die folgenden Importe ausführen.


In [6]:
import pandas as pd # data structures; see https://pandas.pydata.org/
import numpy as np # large, multi-dimensional arrays and matrices; see https://numpy.org/
import time
from scipy.stats import pearsonr, spearmanr, chi2_contingency
import warnings # we will ignore interpreter outputs that are warnings only (error messages will still be shown)
warnings.filterwarnings("ignore")

# as you can see above, you can enter comments using the hashtag sign

## 3. Python-Liste versus NumPy-Array
### a) Große Python-Liste erstellen


In [11]:
size = 10_000_0000  # Anzahl der Elemente (kann verändert werden)
python_list = list(range(size))

### b) NumPy-Array erstellen

In [12]:
numpy_array = np.arange(size)

### c) Quadrieren + Zeitmessung

In [13]:
# Python-Liste (mit Schleife)
start = time.time()

python_result = []
for x in python_list:
    python_result.append(x ** 2)

python_time = time.time() - start


# NumPy-Array (vektorisiert)
start = time.time()

numpy_result = numpy_array ** 2

numpy_time = time.time() - start

### d) Ergebnisse Anzeigen

In [14]:
print("Zeit Python-Liste:", python_time, "Sekunden")
print("Zeit NumPy-Array:", numpy_time, "Sekunden")

Zeit Python-Liste: 15.652081727981567 Sekunden
Zeit NumPy-Array: 0.30434513092041016 Sekunden


### &#x270d; Übung
 Größe verändern
Ändere 'size' (z.B. auf 10_000_0000) und beobachte den Unterschied erneut.")

## 4. NumPy: Auf Array-Elemente zugreifen (Indexing)

### a) Zugriff auf ein Element an Stelle X

Der Index beginnt bei Python immer bei 0.

In [15]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[2])  # Element an Position 2

30


### b) Intervalle auswählen (Slicing)

In [22]:
print(arr[1:4])

[20  0 40]


### c) Jeden 2. Wert auf Null setzen

::2 bedeutet:  vom Anfang bis Ende in 2er-Schritten

Dadurch wird jedes zweite Element ausgewählt.`

In [17]:
arr[::2] = 0
print(arr)

[ 0 20  0 40  0]


### &#x270d; Übung

Generieren Sie ein 2D NumPy-Array mit der Form (10, 10), das Zahlen von 1 bis 100 in aufsteigender Reihenfolge enthält. Nutzen Sie dazu die Funktion np.arange und np.reshape. Die Implementierung ist schon vorbereitet, s. unten.

a) Extrahieren Sie die erste, fünfte und letzte Zeile des Arrays.

b) Wählen Sie alle Elemente der 3. und 7. Spalte aus, die in ungeraden Zeilen stehen
(erinnern Sie sich, dass die Indexierung bei 0 beginnt).

c) Wählen Sie ein 3x3-Subarray aus, das linke obere Ecke Ihres ursprünglichen Arrays enthält.

d) Ändern Sie jedes Element in der 2. und 4. Zeile Ihres Arrays, indem Sie es durch seinen negativen Wert ersetzen.

e) Ersetzen Sie alle Elemente, die kleiner als 25 sind im Array durch 0

In [20]:
# Array von 1 bis 100 erzeugen und in 10x10 umformen
a = np.arange(1, 101).reshape(10, 10)

print("Originales Array:\n")
print(a)

## HIER bitte Aufgaben a) bis e) ergänzen
print("aufgabe a")
print(a[0], a[3], a[-1])

print("aufgabe b")
ergebnis = a[1::2, [2, 6]]
print(ergebnis)

Originales Array:

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
aufgabe a
[ 1  2  3  4  5  6  7  8  9 10] [31 32 33 34 35 36 37 38 39 40] [ 91  92  93  94  95  96  97  98  99 100]
aufgabe b
[[13 17]
 [33 37]
 [53 57]
 [73 77]
 [93 97]]


## 5. Pandas



### a) Daten einlesen

In [ ]:
data = {
    "Lernstunden_pro_Woche": [5, 10, 2, 15, 8, 12, 4, 9, 11, 3],
    "Anwesenheit_in_Prozent": [60, 95, 50, 100, 80, 90, 55, 85, 92, 40],
    "Pruefungsdauer_in_Minuten": [30, 45, 25, 50, 35, 40, 28, 38, 42, 20],
    "Bestanden": [0, 1, 0, 1, 1, 1, 0, 1, 1, 0]  # 1 = bestanden, 0 = durchgefallen
}

df = pd.DataFrame(data)
df.head()

### b) Daten analysieren


In [ ]:
# Anzeige der Spaltenbezeichnungen
print('Spalten: ', df.columns)

# Index - Zeilen haben typischerweise einen numerischen Index, können aber z.B. auch vom Typ String sein
print(df.index)

In [ ]:
# Übersicht und statistische Werte
df.describe()

In [ ]:
# Überblick über Datentypen und fehlende Werte
df.info()

### Dokumentation

Möchten Sie mehr über einen Befehl erfahren und wissen, wie er funktioniert? Führen Sie einfach Folgendes aus, und Jupyter zeigt Ihnen die entsprechende Dokumentation an!

Fügen Sie einfach ein Fragezeichen (?) an eine Variable oder einen Befehl an und führen Sie die Zelle aus, um die zugehörige Dokumentation auszugeben. Hinweis: Sie können die Autovervollständigungsfunktion interaktiv nutzen, indem Sie den Cursor in eine Zelle setzen und die Tab-Taste drücken.


In [ ]:
df.head?

### c) Filtern und Manipulieren

In [ ]:
# Filter: Nur bestandene Studenten
df[df["Bestanden"] == 1]

# Filter: Studenten mit mehr als 10 Lernstunden
print ([df["Lernstunden_pro_Woche"] > 10])

# Hypothese prüfen: Mehr Lernen → besseres Bestehen?
df.groupby("Bestanden")["Lernstunden_pro_Woche"].mean()

# Durchschnittliche Anwesenheit je Bestehensstatus
df.groupby("Bestanden")["Anwesenheit_in_Prozent"].mean()



### &#x270d; Übung

Prüfen Sie die durchschnittliche Prüfungsdauer je Bestehen


In [ ]:
# Übung

# Durchschnittliche Prüfungsdauer je Bestehensstatus
df.groupby("Bestanden")["Pruefungsdauer_in_Minuten"].mean()

